### DISCUSSION TITLE
Headplane not reachable when connected

### DISCUSSION THREAD

**Discussion by tobehn** [tale/headplane#140] [Support]
I have installed headscale with headplane behind traefik reverse proxy and am pretty happy with it.
Thank you very much for building this software.

However, when i am connected to the tailnet i cannot reach the /admin UI via the set URI. Is this the default behaviour?
Do i need to set special DNS settings or traefik labels?

When i traceroute my URI while being connected i get this message:
`Cannot handle "host" cmdline arg `example.com' on position 1 (argc 1)`

**Comment by tale** [comment]
Can you post a redacted version of your setup. I want to see your Traefik tags.

**Comment by tobehn** [comment]
Sure, this is my configuration besides other services on that traefik.
The headscale URL is left like "http://headscale:8080" for headplane.
Traefik successfully gets Lets Encrypt for the service.


```
  headscale:
    container_name: headscale
    image: headscale/headscale
    command: serve
    restart: always
    ports:
      - "8080:8080"
    networks:
      - web
    volumes:
      - "./headscale/data:/var/lib/headscale"
      - "./headscale/config.yml:/etc/headscale/config.yaml"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.headscale.rule=Host(`connect.example.com`)"
      - "traefik.http.routers.headscale.entrypoints=websecure"
      - "traefik.http.routers.headscale.tls.certresolver=myresolver"
      - "traefik.http.services.headscale.loadbalancer.server.port=8080"

  headplane:
    container_name: headplane
    image: ghcr.io/tale/headplane:0.3.2
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - web
    depends_on:
      - headscale
    volumes:
      - "./headscale/config.yml:/etc/headscale/config.yaml"
    environment:
      HEADSCALE_URL: 'http://headscale:8080'
      API_KEY: "secret"
      CONFIG_FILE: "/etc/headscale/config.yaml"
      COOKIE_SECRET: 'secret'
      DISABLE_API_KEY_LOGIN: 'true'
      COOKIE_SECURE: 'false'
      HOST: '0.0.0.0'
      PORT: '3000'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.headplane.rule=Host(`connect.example.com`) && PathPrefix(`/admin`)"
      - "traefik.http.routers.headplane.entrypoints=websecure"
      - "traefik.http.routers.headplane.tls.certresolver=myresolver"
      - "traefik.http.services.headplane.loadbalancer.server.port=3000"
```

**Comment by tobehn** [comment]
ok, i just gave the headplane its own subdomain.

`headplane.example.com` and deleted the PathPrefix.
Now i am able to access the webinterface even though i am connected to `connect.example.com`

```
 headscale:
    container_name: headscale
    image: headscale/headscale
    command: serve
    restart: always
    ports:
      - "8080:8080"
    networks:
      - web
    volumes:
      - "./headscale/data:/var/lib/headscale"
      - "./headscale/config.yml:/etc/headscale/config.yaml"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.headscale.rule=Host(`connect.example.com`)"
      - "traefik.http.routers.headscale.entrypoints=websecure"
      - "traefik.http.routers.headscale.tls.certresolver=myresolver"
      - "traefik.http.services.headscale.loadbalancer.server.port=8080"

  headplane:
    container_name: headplane
    image: ghcr.io/tale/headplane:0.3.2
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - web
    depends_on:
      - headscale
    volumes:
      - "./headscale/config.yml:/etc/headscale/config.yaml"
    environment:
      HEADSCALE_URL: 'http://headscale:8080'
      API_KEY: "secret"
      CONFIG_FILE: "/etc/headscale/config.yaml"
      COOKIE_SECRET: 'secret'
      DISABLE_API_KEY_LOGIN: 'true'
      COOKIE_SECURE: 'false'
      HOST: '0.0.0.0'
      PORT: '3000'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.headplane.rule=Host(`headplane.example.com`)"
      - "traefik.http.routers.headplane.entrypoints=websecure"
      - "traefik.http.routers.headplane.tls.certresolver=myresolver"
      - "traefik.http.services.headplane.loadbalancer.server.port=3000"
```
