### DISCUSSION TITLE
Need complete docker-compose.yml  sample file

### DISCUSSION THREAD

**Discussion by ligolas** [tale/headplane#208] [Support] [answered]
### Description

It's seems I can't find a complete version of `docker-compose.yml` From `docs/Integrated-Mode.md` I got the main part of the file, and from issues submitted by other users, I can finds there envs with `# This is always required for Headplane to work` comment. It seems that these users got it from somewhere else not exists in current version

**Comment by ky-bd** [comment, marked as answer]
I believe that the compose file in the docs is already 'complete' without the need for any extra envs. If you are referring to https://github.com/tale/headplane/issues/82#issuecomment-2629419142 , maybe it's an older version (prior to 0.5) of headplane which is configured with envs instead of the config.yaml file (see [CHANGELOG](https://github.com/tale/headplane/blob/main/CHANGELOG.md#05-february-27-2025)).

If you would like a more 'complete' one, here is mine, FYI. In addition to the headplane and headscale, it includes [Caddy](https://caddyserver.com/) as the reverse proxy, [headscale-ui](https://github.com/gurucomputing/headscale-ui) as an alternative control panel (static web pages mapped into the caddy container; I find it more convenient when managing tags and routes), and [litestream](https://litestream.io/) for encrypted backup headscale database to Cloudflare R2 storage bucket.

compose.yml:

```yaml
services:
  headplane:
    # I recommend you pin the version to a specific release
    image: ghcr.io/tale/headplane:0.5.10
    container_name: headplane
    restart: unless-stopped
    expose:
      - "3000/tcp" # headplane server port
    volumes:
      - "./headplane/config.yaml:/etc/headplane/config.yaml"
      # This should match headscale.config_path in your config.yaml
      - "./headscale/config/config.yaml:/etc/headscale/config.yaml"
      # Headplane stores its data in this directory
      - "./headplane/data:/var/lib/headplane"
      # If you are using the Docker integration, mount the Docker socket
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  headscale:
    image: headscale/headscale:0.25.1
    container_name: headscale
    restart: unless-stopped
    command: serve
    expose:
      - "8080/tcp" # headscale listen_addr port
    ports:
      - "3478:3478/udp" # STUN port in headscale config
    volumes:
      - ./headscale/data:/var/lib/headscale
      - ./headscale/config:/etc/headscale
      - headscale_sock:/var/run/headscale
  caddy:
    image: caddy/caddy:latest
    ports:
      - "8443:8443/tcp" # server_url in headscale config
    volumes:
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ./caddy/conf:/etc/caddy
      - ./headscale-ui:/headscale-ui # https://github.com/gurucomputing/headscale-ui
  litestream:
    image: litestream/litestream:latest
    restart: unless-stopped
    command: replicate
    volumes:
      - ./headscale/data:/data
      - ./litestream/litestream.yml:/etc/litestream.yml
volumes:
  headscale_sock:
```

Caddyfile:

```Caddyfile
# Headscale server_url
headscale.example.com:8443 {
	handle /web* {
		root /headscale-ui
		file_server
	}
	redir /admin /admin/
	handle /admin/* {
		reverse_proxy headplane:3000
	}
	handle {
		reverse_proxy headscale:8080
	}
}
```

litestream.yml:

```yaml
dbs:
  - path: /data/db.sqlite
    replicas:
      - type: s3
        endpoint: https://REDACTED.r2.cloudflarestorage.com/
        bucket: REDACTED
        access-key-id: REDACTED
        secret-access-key: REDACTED
        sync-interval: 60s
        snapshot-interval: 1h
        age:
          recipients:
            - ageredacted
          identities:
            - AGE-SECRET-KEY-REDACTED
```
