### DISCUSSION TITLE
Failed to get machines with `Unexpected Server Error`

### DISCUSSION THREAD

**Discussion by leoncamel** [tale/headplane#222] [Support] [answered]
I got an error on Machines page, the log looks like this:

```
headplane  | 2025-05-21T20:11:18.253Z [api] DEBUG: GET v1/routes failed with status 404                                                                                       
headplane  | ResponseError: Response Error (404): {"code":5,"message":"Not Found","details":[]}                                                                               
headplane  |     at ApiClient.get (file:///app/build/server/assets/index-CD2MsUX2.js:234777:13)                                                                               
headplane  |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)                                                                               
headplane  |     at async Promise.all (index 1)                                                                                                                               
headplane  |     at async loader$5 (file:///app/build/server/assets/server-build.js:53530:37)                                                                                 
headplane  |     at async callRouteHandler (file:///app/build/server/assets/index-CD2MsUX2.js:10343:16)                                                                       
headplane  |     at async commonRoute.loader (file:///app/build/server/assets/index-CD2MsUX2.js:10452:19)                                                                     
headplane  |     at async file:///app/build/server/assets/index-CD2MsUX2.js:7108:19                                                                                           
headplane  |     at async callLoaderOrAction (file:///app/build/server/assets/index-CD2MsUX2.js:7158:16)                                                                      
headplane  |     at async Promise.all (index 2)                                                                                                                               
headplane  |     at async defaultDataStrategy (file:///app/build/server/assets/index-CD2MsUX2.js:6943:17) {                                                                   
headplane  |   status: 404,                                                                                                                                                   
headplane  |   response: '{"code":5,"message":"Not Found","details":[]}',
headplane  |   responseObject: { code: 5, message: 'Not Found', details: [] }                                                                                                 
headplane  | }  
```

And my traefik config:

```
http:
  middlewares:
    # Existing middlewares
    redirect-to-https:
      redirectScheme:
        scheme: https

    # Root path redirect middleware for Headscale
    headscale-redirect:
      redirectRegex:
        regex: "^(https?://[^/]+)/?$"
        replacement: "${1}/admin"
        permanent: true

    # Admin path rewriting middleware for Headplane
    headscale-rewrite-admin:
      addPrefix:
        prefix: "/admin"

    # CORS middleware for Headscale API
    cors:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
          - POST
        accessControlAllowHeaders:
          - "*"
        accessControlAllowOriginList:
          - "https://headscale.myhome.com"
        accessControlMaxAge: 100
        addVaryHeader: true

    # Basic auth middleware for Traefik dashboard (optional)
    traefik-dashboard-auth:
      basicAuth:
        users:
          # Generate this with: htpasswd -nb admin YOUR_PASSWORD
          - "admin:abc"

  routers:
    # Your existing Pangolin routers here
    main-app-router-redirect:
      rule: "Host(`pangolin.myhost.com`)"
      service: next-service
      entryPoints:
        - web
      middlewares:
        - redirect-to-https

    next-router:
      rule: "Host(`pangolin.myhost.com`) && !PathPrefix(`/api/v1`)"
      service: next-service
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    api-router:
      rule: "Host(`pangolin.myhost.com`) && PathPrefix(`/api/v1`)"
      service: api-service
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    ws-router:
      rule: "Host(`pangolin.myhost.com`)"
      service: api-service
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    # Headscale API router - for all non-admin paths
    headscale-api-rtr:
      rule: "Host(`headscale.myhost.com`) && !PathPrefix(`/admin`)"
      service: headscale-direct-svc
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      middlewares:
        - cors

    # Headplane admin interface router
    headplane-admin-rtr:
      rule: "Host(`headscale.myhost.com`) && PathPrefix(`/admin`)"
      service: headplane-direct-svc
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    # Root path redirection router
    headscale-root-rtr:
      rule: "Host(`headscale.myhost.com`) && Path(`/`)"
      service: noop@internal
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      middlewares:
        - headscale-redirect
      priority: 100 # Make this higher priority than other rules

    # Tailscale subdomain handler
    # headscale-ts-rtr:
    #   rule: "HostRegexp(`{subdomain:[a-zA-Z0-9-]+}.ts.myhost.com`)"
    #   service: headscale-direct-svc
    #   entryPoints:
    #     - websecure
    #   tls:
    #     certResolver: letsencrypt

    # Traefik dashboard access (optional)
    traefik-dashboard-rtr:
      rule: "Host(`traefik.myhost.com`)"
      service: api@internal
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      middlewares:
        - traefik-dashboard-auth

  services:
    # Your existing Pangolin services
    next-service:
      loadBalancer:
        servers:
          - url: "http://pangolin:3002" # Next.js server

    api-service:
      loadBalancer:
        servers:
          - url: "http://pangolin:3000" # API/WebSocket server

    # Headscale services
    headscale-direct-svc:
      loadBalancer:
        servers:
          - url: "http://headscale:8080" # Points directly to Headscale container

    headplane-direct-svc:
      loadBalancer:
        servers:
          - url: "http://headplane:3000" # Points directly to Headplane container

    headplane-redirect-svc:
      loadBalancer:
        servers:
          - url: "http://headplane:3000" # For root redirect to admin

  serversTransports:
    insecureTransport:
      insecureSkipVerify: true
```

Any hints about it? Thanks.
