### DISCUSSION TITLE
Error while validating API key: DataWithResponseInit

### DISCUSSION THREAD

**Discussion by imblowsnow** [tale/headplane#249] [Support]
### Description

2025-06-15T08:46:24.202Z [server] INFO: Running Node.js 22.16.0
2025-06-15T08:46:24.227Z [config] INFO: Found a valid configuration file at /etc/headplane/config.yaml
2025-06-15T08:46:24.250Z [config] INFO: Found a valid Headscale configuration file at /etc/headscale/config.yaml
2025-06-15T08:46:24.264Z [config] INFO: Using Docker integration
2025-06-15T08:46:24.264Z [config] INFO: Checking socket: /var/run/docker.sock
2025-06-15T08:46:24.305Z [config] INFO: Using container: /headscale (ID: 8495a3c4eb7eaeffd2caf4f552ebbdef316d621d0945c8032b4bfa9d6a1edcf7)
2025-06-15T08:46:24.319Z [server] INFO: Running on 0.0.0.0:3000
2025-06-15T08:46:48.581Z [auth] ERROR: Error while validating API key: DataWithResponseInit {
  type: 'DataWithResponseInit',
  data: 'The Headscale API is not reachable',
  init: [Object]
}

### Headplane Version

0.6.0

### Headscale Version

0.26.0

**Comment by imblowsnow** [comment]
Now apikey has been verified successfully.

![Image](https://github.com/user-attachments/assets/18439881-72d3-4580-9b34-db3adaf0f81b)

![Image](https://github.com/user-attachments/assets/d02c77a1-e0e6-4292-88b7-50d88a233598)

**Comment by imblowsnow** [comment]
@tale can you help me ?

**Comment by tale** [comment]
> The Headscale API is not reachable
This is what your error says, Headplane cannot connect to Headscale correctly. Validate your config and try again. This also is not worthy of an issue, please open a discussion next time. 🙄

**Reply by Nordlicht-13** [reply]
> > The Headscale API is not reachable
> > This is what your error says, Headplane cannot connect to Headscale correctly. Validate your config and try again.

Can you give a hint, what the problem might be?
I have this in the config.yaml:
```
 docker:
    enabled: true
    container_label: "me.tale.headplane.target=headscale"
    container_name: "headscale"
    socket: "unix:///var/run/docker.sock"
``` 
and this in the docker compose file:
```
services:
  headscale:
    container_name: headscale
    image: docker.io/headscale/headscale:0.26.1
    labels:
      me.tale.headplane.target: headscale
```

**Reply by Nordlicht-13** [reply]
I had to change url under headscale from https://hs.mydomain.com to my local IP http://192.168.XX.XX:Port
```
headscale:
  url: "http://192.168.XX.XX:8880"
  public_url: "https://hs.mydomain.com"
  config_path: "/etc/headscale/config.yaml"
  config_strict: true
```
