### ISSUE TITLE
Headplane cannot resolve DNS queries at times.

### ISSUE THREAD

**Issue by cowbe0x004** [tale/headplane#11]
Trying to set up headplane and getting this error in the log,
```
headplane  | GET /admin/ 302 - - 1.923 ms
headplane  | GET /admin/machines 302 - - 4.647 ms
headplane  | TypeError: Cannot read properties of undefined (reading 'issuer')
headplane  |     at getOidcConfig (file:///app/build/server/index.js?t=1715826667000:492:27)
headplane  |     at getContext (file:///app/build/server/index.js?t=1715826667000:480:19)
headplane  |     at loader$9 (file:///app/build/server/index.js?t=1715826667000:605:20)
headplane  |     at Object.callRouteLoader (/app/node_modules/.pnpm/@remix-run+server-runtime@2.9.2_typescript@5.4.5/node_modules/@remix-run/server-runtime/dist/data.js:66:16)
headplane  |     at /app/node_modules/.pnpm/@remix-run+router@1.16.1/node_modules/@remix-run/router/router.ts:4266:21
headplane  |     at callLoaderOrAction (/app/node_modules/.pnpm/@remix-run+router@1.16.1/node_modules/@remix-run/router/router.ts:4328:16)
headplane  |     at async Promise.all (index 0)
headplane  |     at callDataStrategyImpl (/app/node_modules/.pnpm/@remix-run+router@1.16.1/node_modules/@remix-run/router/router.ts:4169:17)
headplane  |     at callDataStrategy (/app/node_modules/.pnpm/@remix-run+router@1.16.1/node_modules/@remix-run/router/router.ts:3503:19)
headplane  |     at loadRouteData (/app/node_modules/.pnpm/@remix-run+router@1.16.1/node_modules/@remix-run/router/router.ts:3447:19)
headplane  | GET /admin/login 500 - - 10.136 ms
```

Page shows "unexpected server error".

This is my docker-compose,
```
  headscale:
    image: headscale/headscale:0.23.0-alpha11
    container_name: headscale
    volumes:
      - ./headscale/config:/etc/headscale/
      - ./headscale/data:/var/lib/headscale
    #ports:
     # - 8080:8080
    command: serve
    restart: unless-stopped
    networks:
      reverseproxy-nw:

  headplane:
    container_name: headplane
    image: ghcr.io/tale/headplane:latest
    restart: unless-stopped
    volumes:
      - './headscale/data:/var/lib/headscale'
      - './headscale/config:/etc/headscale'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    ports:
      - '3000:3000'
    networks:
      reverseproxy-nw:
    environment:
      # This is always required for Headplane to work
      COOKIE_SECRET: 'BunchFabulousGalvanizeHardcore'
      #CONFIG_FILE: './headscale/config/config.yaml'
      HEADSCALE_CONTAINER: 'headscale'
      DISABLE_API_KEY_LOGIN: 'true'
      HOST: '0.0.0.0'
      PORT: '3000'
```

Please let me know if you know what might be causing this, thank you.
