### ISSUE TITLE
Authentik OIDC not working on 5.2

### ISSUE THREAD

**Issue by B08Z** [tale/headplane#115]
Configuration was previously working on 4.2 no issues 
OIDC for both headscale and Headplane.

No errors during docker compose up. Config read correctly but trying to login with SSO gets following error 

{
  "code": "OAUTH_RESPONSE_BODY_ERROR",
  "error": {
    "name": "invalid_client",
    "description": "Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)"
  }
}

Any help welcome

**Comment by B08Z** [comment]
Thanks for the speedy reply. 

I have set it to basic in Headplane config no luck same error. 

I'll post full config when at a computer 


Thanks again, awesome project!

**Comment by B08Z** [comment]
After regonfiguring Authentik I now recieve the following error in the browser:

`{"code":500,"error":{"name":"Internal Server Error","description":"An unknown error occurred"}}`

And docker headplane error logs shows:

`headplane  | 2025-03-01T22:18:47.267Z (INFO) [SRVX] Running Node.js 22.14.0
headplane  | 2025-03-01T22:18:47.270Z (INFO) [SRVX] Found dependencies
headplane  | 2025-03-01T22:18:47.271Z (INFO) [CFGX] Headplane configuration found at /etc/headplane/config.yaml
headplane  | 2025-03-01T22:18:47.378Z (INFO) [SRVX] Running on 0.0.0.0:3000
headplane  | 2025-03-01T22:20:00.933Z (INFO) [CFGX] Headplane configuration found at /etc/headplane/config.yaml
headplane  | 2025-03-01T22:20:00.972Z (INFO) [SRVX] Using build directory /app/build
headplane  | 2025-03-01T22:20:05.838Z (INFO) [INTG] Using Docker integration
headplane  | 2025-03-01T22:20:05.840Z (INFO) [INTG] Using container: headscale
headplane  | 2025-03-01T22:20:05.841Z (INFO) [INTG] Checking socket: /var/run/docker.sock
headplane  | 2025-03-01T22:20:05.966Z (INFO) [CFGX] Headscale configuration found at /etc/headscale/config.yaml
headplane  | 2025-03-01T22:20:07.443Z (ERRO) [OIDC] Unknown error: ClientError: unsupported operation
headplane  |     at e (file:///app/node_modules/.pnpm/openid-client@6.1.7/node_modules/openid-client/build/index.js:71:12)
headplane  |     at errorHandler (file:///app/node_modules/.pnpm/openid-client@6.1.7/node_modules/openid-client/build/index.js:106:15)
headplane  |     at Module.authorizationCodeGrant (file:///app/node_modules/.pnpm/openid-client@6.1.7/node_modules/openid-client/build/index.js:681:9)
headplane  |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
headplane  |     at async finishAuthFlow (file:///app/build/server/index.js:870:18)
headplane  |     ... 3 lines matching cause stack trace ...
headplane  |     at async file:///app/node_modules/.pnpm/react-router@7.1.1_react-dom@19.0.0_react@19.0.0__react@19.0.0/node_modules/react-router/dist/development/chunk-K6AXKMTT.mjs:3398:19
headplane  |     at async callLoaderOrAction (file:///app/node_modules/.pnpm/react-router@7.1.1_react-dom@19.0.0_react@19.0.0__react@19.0.0/node_modules/react-router/dist/development/chunk-K6AXKMTT.mjs:3448:16) {
headplane  |   code: 'OAUTH_UNSUPPORTED_OPERATION',
headplane  |   [cause]: [UnsupportedOperationError]
headplane  | }`

**Comment by B08Z** [comment]
Using the API key to sign in works as expected.

**Comment by tale** [comment]
Here, this is my Authelia configuration if this helps
```yaml
      - client_id: 'headscale'
        client_name: 'Tailscale'
        public: false
        authorization_policy: 'two_factor'
        redirect_uris:
          - 'https://***/oidc/callback'
          - 'https://***/admin/oidc/callback'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
        userinfo_signed_response_alg: 'none'
        client_secret: ***
```
