### ISSUE TITLE
I cannot press Confirm while adding new device

### ISSUE THREAD

**Issue by mac-lucky** [tale/headplane#116]
![Image](https://github.com/user-attachments/assets/465a6928-73e8-45a4-ad2c-8e6d83ca178c)

Why is it blocked out? 

Is this cause of this ?
```
2025-03-01T14:51:37.794Z (INFO) [INTG] Checking pod headscale in namespace headscale (https://10.96.0.1:443)
2025-03-01T14:51:38.391Z (ERRO) [INTG] Failed to read pod info: HttpError: HTTP request failed
    at Request._callback (/app/node_modules/.pnpm/@kubernetes+client-node@0.22.3/node_modules/@kubernetes/client-node/dist/gen/api/coreV1Api.js:15080:36)
    at self.callback (/app/node_modules/.pnpm/request@2.88.2/node_modules/request/request.js:185:22)
    at Request.emit (node:events:518:28)
    at Request.<anonymous> (/app/node_modules/.pnpm/request@2.88.2/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:518:28)
    at IncomingMessage.<anonymous> (/app/node_modules/.pnpm/request@2.88.2/node_modules/request/request.js:1076:12)
```

Here is my headplane config in kubernetes:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: headplane-config
  namespace: headscale
data:
  config.yaml: |
    # Configuration for the Headplane server and web application
    server:
        host: "0.0.0.0"
        port: 3000

        # The secret used to encode and decode web sessions
        # Ensure that this is exactly 32 characters long
        cookie_secret: "<change_me_to_something_secure!>"

        # Should the cookies only work over HTTPS?
        # Set to false if running via HTTP without a proxy
        # (I recommend this is true in production)
        cookie_secure: false

    # Headscale specific settings to allow Headplane to talk
    # to Headscale and access deep integration features
    headscale:
        # The URL to your Headscale instance
        # (All API requests are routed through this URL)
        url: "http://127.0.0.1:8080"

        # Optional, public URL if they differ
        # This affects certain parts of the web UI

        # Path to the Headscale configuration file
        # This is optional, but HIGHLY recommended for the best experience
        # If this is read only, Headplane will show your configuration settings
        # in the Web UI, but they cannot be changed.
        config_path: "/etc/headscale/config.yaml"

        # Headplane internally validates the Headscale configuration
        # to ensure that it changes the configuration in a safe way.
        # If you want to disable this validation, set this to false.
        config_strict: true

    # Integration configurations for Headplane to interact with Headscale
    # Only one of these should be enabled at a time or you will get errors
    integration:
        docker:
            enabled: false
            container_name: "headscale"
        kubernetes:
            enabled: true
            validate_manifest: true
            pod_name: "headscale"
        proc:
            enabled: false

    # OIDC Configuration for simpler authentication
    # (This is optional, but recommended for the best experience)
    # oidc:
    #     issuer: "https://accounts.google.com"
    #     client_id: "your-client-id"
    #     client_secret: "<your-client-secret>"
    #     disable_api_key_login: false
    #     token_endpoint_auth_method: "client_secret_post"

    #     # If you are using OIDC, you need to generate an API key
    #     # that can be used to authenticate other sessions when signing in.
    #     #
    #     # This can be done with `headscale apikeys create --expiration 999d`
    #     headscale_api_key: "<your-headscale-api-key>"

    #     # Optional, but highly recommended otherwise Headplane
    #     # will attempt to automatically guess this from the issuer
    #     #
    #     # This should point to your publicly accessibly URL
    #     # for your Headplane instance with /admin/oidc/callback
    #     redirect_uri: "http://localhost:3000/admin/oidc/callback"
```
