### ISSUE TITLE
Integrated Mode - `/admin` path

### ISSUE THREAD

**Issue by ortonomy** [tale/headplane#120]
I'm not sure how this container is expected to be used. If it's behind a reverse proxy and I want to put it on a path like `/ui/headplane/*` how can I do it? When I visit `/tools/headplane/admin` it tries to redirect me to `/admin/machines` and then 404s. 

Anyone else managed to get this working on a reverse proxy?

**Comment by tale** [comment]
You'd need to explicitly support a rewrite.

**Comment by Lite5h4dow** [comment]
@ortonomy the tailscale implimentation has the UI on /admin . the clients on windows, macOS, iOS and android all direct you to /admin you would have to handle the route changes in your proxy.

**Comment by ortonomy** [comment]
> You'd need to explicitly support a rewrite.

so I tried doing this. I got it to rewrite all `/ui/headplane/admin` to downstream `/admin` but then the downstream wants to rewrite to `/admin/machines`. 

I don't really get what needs to be done. What if I have multiple apps running on the same server. I don't want one to force itself onto /admin

**Comment by Lite5h4dow** [comment]
> you mean for authentication or for managing your tailnet through the apps?

just authentication, at least for now, can worry about the other stuff once there is a basic working implimentation

**Comment by high3eam** [comment]
@ortonomy 
I use Caddy as a reverse proxy and headscale + headplane UI as docker services.

Caddyfile reverse proxy config:
```
headscale.example.com {
        reverse_proxy /admin* localhost:5678
        reverse_proxy * localhost:1234
}
```
docker-compose.yaml:
```yaml
services:
    headscale:
        container_name: headscale
        volumes:
            - ./config:/etc/headscale/
            - ./keys:/var/lib/headscale/
        ports:
            - localhost:1234:8080
            - 9090:9090
        image: headscale/headscale:v0.25.1
        command: serve
        restart: unless-stopped
    headplane:
        image: ghcr.io/tale/headplane:0.5.3
        container_name: headplane-ui
        restart: unless-stopped
        ports:
            - localhost:5678:3000
        volumes:
            - './headplane/config.yaml:/etc/headplane/config.yaml'
            - './config/config.yaml:/etc/headscale/config.yaml'
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
```

All requests towards `headscale.example.com` are routed to the **headscale docker service**, all requests to `headscale.example.com/admin` are routed to **headplane docker service**.
