### ISSUE TITLE
Ignore missing headscale TLS configuration

### ISSUE THREAD

**Issue by schliz** [tale/headplane#136]
Headplane can't handle missing tls configuration. Related to #118 

I run headscale and headplane behind a reverse proxy which handles all things TLS-related. My headscale config looks like this:

```yaml
[...]

tls_cert_path: ""
tls_key_path: ""

#acme_url: https://acme-v02.api.letsencrypt.org/directory
#acme_email: "email@example.org"
#tls_letsencrypt_hostname: "example.com"
```

I have commented out the ACME options so headscale runs as HTTP-only ([see headscale docs](https://github.com/juanfont/headscale/blob/main/docs/ref/integration/reverse-proxy.md#tls)).  Headplane shows this error:

    (ERRO) [CFGX] Error parsing Headscale configuration:
    (ERRO) [CFGX]  (0): acme_email must be a string (was missing)
    (ERRO) [CFGX]  (1): tls_letsencrypt_hostname must be a string (was missing)

This also happens in non-strict mode.

Headplane will only read the config properly, if these options are set. Headscale however breaks, because it now expects HTTPS requests. Why does headplane require these options to be set, can they just be ignored?

Thank you in advance
