### ISSUE TITLE
DNS page should have split DNS configuration.

### ISSUE THREAD

**Issue by gageorsburn** [tale/headplane#14]
Right now only the main DNS configuration is allowed to be configured, however headscale supports split DNS configuration.

```
dns_config:
  # Whether to prefer using Headscale provided DNS or use local.
  override_local_dns: true

  # List of DNS servers to expose to clients.
  nameservers:
    - 1.1.1.1

  restricted_nameservers:
    foo.bar.io:
      - 100.64.0.1
```
