### ISSUE TITLE
Add UI support for managing AAAA records in Headscale DNS

### ISSUE THREAD

**Issue by arksunix** [tale/headplane#189]
### Description

[Headscale DNS](https://headscale.net/stable/ref/dns/) supports not only A records, but also AAAA records. This is useful as a workaround until [MagicDNS adds support for AAAA records](https://github.com/tailscale/tailscale/issues/1152). I already use AAAA records by configuring them manually in the Headscale config file, but it would be great to have support for managing them directly in the UI.

**Comment by tale** [comment]
I was not aware `AAAA` is supported, let me add it

**Comment by tale** [comment]
@arksunix Please test with the `ghcr.io/tale/headplane:next` image, it should be supported now.

> Interested in beta testing? Subscribe to the [Pre-release Testing](https://github.com/tale/headplane/discussions/176) discussion to be notified about future testing release. As always, pre-release versions are accessible on Docker via `ghcr.io/tale/headplane:next` or the `next` tag on Git.

**Comment by arksunix** [comment]
@tale Now I can see the records that I added earlier, but when I try to add a new record, it only creates an A record.
Even if I paste an IPv6 address, it still sets _type: "A"_ in the config.

**Comment by tale** [comment]
Sorry, I had to make a few changes, please wait for the action to finish:
https://github.com/tale/headplane/actions/runs/14683613812/job/41209377936?pr=175

It'll then allow you to pick between A or AAAA on the UI via a dropdown.

**Comment by arksunix** [comment]
Now it doesn’t display any records on the page (even though the config contains records), and when I try to add a new record (A or AAAA), it doesn’t do anything — it neither adds the record to the page nor updates the config.

**Comment by tale** [comment]
Can you share a redacted Headscale config with me.

**Comment by arksunix** [comment]
Here extra DNS records from my headscale config:
```
  # Extra DNS records
  # so far only A and AAAA records are supported (on the tailscale side)
  # See: docs/ref/dns.md
  extra_records:
    - name: vault.hades.ts.int
      type: A
      value: 100.64.0.4
    - name: zeus.ts.int
      type: AAAA
      value: fd7a:115c:a1e0::1
    - name: hestia.ts.int
      type: AAAA
      value: fd7a:115c:a1e0::3
    - name: hades.ts.int
      type: AAAA
      value: fd7a:115c:a1e0::4
  #   - name: "grafana.myvpn.example.com"
  #     type: "A"
  #     value: "100.64.0.3"
  #
  #   # you can also put it in one line
  #   - { name: "prometheus.myvpn.example.com", type: "A", value: "100.64.0.3" }
  #
  # Alternatively, extra DNS records can be loaded from a JSON file.
  # Headscale processes this file on each change.
  # extra_records_path: /var/lib/headscale/extra-records.json
```
