### ISSUE TITLE
OIDC "client_secret_path" doesn't seem to work

### ISSUE THREAD

**Issue by kimberlyeet** [tale/headplane#199]
### Description

I'm trying to authenticate with Authelia. While setting the client secret directly via `client_secret` works, using `client_secret_path` fails despite the file existing with the correct value.

I already have:
- set the secret in my compose file
- verified in the container that it exists at "/run/secrets/headplane-oidc"
- confirmed the file contains the correct client secret value
- verified that the secret works when set in plaintext via `client_secret`

Headplane error in browser after approving my login in Authelia:
> {"code":"OAUTH_RESPONSE_BODY_ERROR","error":{"name":"invalid_client","description":"Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)."}}

Authelia logs show:
> ERR | method=POST msg=Access Request failed with error: Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method). The provided client secret did not match the registered client secret.

#### Headplane configuration:
```yaml
oidc:
  issuer: https://oidc.mydomain.com
  client_id: redacted
  client_secret_path: /run/secrets/headplane-oidc
  disable_api_key_login: false
  token_endpoint_auth_method: client_secret_post
  headscale_api_key: "redacted"
  redirect_uri: https://tailnet.mydomain.com/admin/oidc/callback
  user_storage_file: "/var/lib/headplane/users.json"
```
#### Authelia configuration:
```yaml
      - client_id: redacted
        client_name: Headplane
        client_secret: redacted
        public: false
        authorization_policy: two_factor
        require_pkce: true
        pkce_challenge_method: 'S256'
        token_endpoint_auth_method: client_secret_post
        redirect_uris:
          - https://tailnet.mydomain.com/admin/oidc/callback
        scopes:
          - openid
          - profile
          - email
          - groups
```

### Headplane Version

0.5.10

### Headscale Version

v0.25.1
