### ISSUE TITLE
Cannot Start Container error mounting "/mnt/containers/headscale/config.yaml"

### ISSUE THREAD

**Issue by W1BTR** [tale/headplane#203]
### Description

I cannot start headplane with the standard config.
`Error response from daemon: Cannot restart container headplane: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/mnt/containers/headscale/config.yaml" to rootfs at "/etc/headplane/config.yaml": create mountpoint for /etc/headplane/config.yaml mount: cannot create subdirectories in "/var/lib/docker/overlay2/051e310dbff53421ac8c911b5001e5eb150ac42c6dd7b71b6d1049fb56336bad/merged/etc/headplane/config.yaml": not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type`

It looks like the docker compose is trying to mount a file called config.yaml. I see no indiciation that this file should exist, and there is no comment for what that should be set to in the example docker-compose. Should this _also_ be set to headscale's config.yaml? 

```
services:
  headplane:
    # I recommend you pin the version to a specific release
    image: ghcr.io/tale/headplane:0.5.10
    container_name: headplane
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - './config.yaml:/etc/headplane/config.yaml'
      # This should match headscale.config_path in your config.yaml
      - './container-config/config.yaml:/etc/headscale/config.yaml'

      # Headplane stores its data in this directory
      - './headplane-data:/var/lib/headplane'

      # If you are using the Docker integration, mount the Docker socket
      - '/var/run/docker.sock:/var/run/docker.sock:ro'

  headscale:
    container_name: headscale
    image: headscale/headscale:0.25.1
    restart: unless-stopped
    # ports:
      # - 8080:8080
    volumes:
      - ./container-config:/etc/headscale
      - ./container-data:/var/lib/headscale
    entrypoint: headscale serve
    networks:
      reverseproxy-nw:

```

### Headplane Version

0.5.10

### Headscale Version

v0.25.1
