### ISSUE TITLE
"Unexpected Server Error" when accessing /admin/machines page ONLY

### ISSUE THREAD

**Issue by yeahthegoys** [tale/headplane#220]
### Description

I can login to the Headplane console using OIDC fine, and all pages load and I'm able to change settings, with the exception of the /admin/machines page.

Below are the logs when I try to load the page:
```
ResponseError: Response Error (404): {"code":5,"message":"Not Found","details":[]}
    at ApiClient.get (file:///app/build/server/assets/index-CD2MsUX2.js:234777:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Promise.all (index 1)
    at async loader$5 (file:///app/build/server/assets/server-build.js:53530:37)
    at async callRouteHandler (file:///app/build/server/assets/index-CD2MsUX2.js:10343:16)
    at async commonRoute.loader (file:///app/build/server/assets/index-CD2MsUX2.js:10452:19)
    at async file:///app/build/server/assets/index-CD2MsUX2.js:7108:19
    at async callLoaderOrAction (file:///app/build/server/assets/index-CD2MsUX2.js:7158:16)
    at async Promise.all (index 2)
    at async defaultDataStrategy (file:///app/build/server/assets/index-CD2MsUX2.js:6943:17) {
  status: 404,
  response: '{"code":5,"message":"Not Found","details":[]}',
  responseObject: { code: 5, message: 'Not Found', details: [] }
}
Resp
```

My config file:
```
server:
  host: "0.0.0.0"
  port: 3000
  cookie_secret: "redacted"
  cookie_secure: true
headscale:
  url: "http://headscale:8080"
  public_url: "redacted"
  config_path: "/etc/headscale/config.yaml"
  config_strict: true
integration:
  docker:
    enabled: true
    container_name: "headscale"
    socket: "unix:///var/run/docker.sock"
oidc:
  issuer: "redacted"
  client_id: "HTfv3jMabo6S77WY7o6KrWUMYMQfwHBGyKt582Xh"
  client_secret: "redacted"
  disable_api_key_login: true
  token_endpoint_auth_method: "client_secret_post"
  headscale_api_key: "redacted"
  redirect_uri: "redacted"
  user_storage_file: "/var/lib/headplane/users.json"
```

Send help plz

### Headplane Version

v.0.5.10

### Headscale Version

using 'latest' tag.
