### ISSUE TITLE
0.6.0 Agent Integration machine versions not updating

### ISSUE THREAD

**Issue by seanob86** [tale/headplane#224]
### Description

I am using the agent integration in 0.6.0. Can see other devices with tailscale version in the UI. However I updated many of my devices from 1.82.5 to 1.84.0, but they still report as 1.82.5 in headplane. Appears the UI will just report versions at a point in time when the agent integration was enabled.

On the updated device the result of `tailscale version` 

```
1.84.0
  tailscale commit: 160c11f37850a7e0a50f5efec48cacc333e69a00-dirty
  go version: go1.24.3
```
config file:
```
integration:
  agent:
    enabled: true
    pre_authkey: [redacted]
    host_name: "Headplane"
    cache_ttl: 60
    cache_path: "/var/lib/headplane/agent_cache.json"
    work_dir: "/var/lib/headplane/agent"
```

agent_cache.json

```
"value": {
            "IPNVersion": "1.82.5",
            "BackendLogID": "redacted",
            "OS": "linux",
            "OSVersion": "6.6.45-11-rpi",
            "Container": false,
            "Distro": "archarm",
            "DistroVersion": "Arch Linux ARM",
            "Desktop": false,
            "DeviceModel": "Raspberry Pi 4 Model B Rev 1.4",
            "Hostname": "pikvm",
            "NoLogsNoSupport": true,
            "Machine": "aarch64",
            "GoArch": "arm64",
            "GoArchVar": "v8.0",
            "GoVersion": "go1.24.2",
```

### Headplane Version

v0.6.0

### Headscale Version

v0.26
