### ISSUE TITLE
OIDC make to support "end_session_endpoint" for after logout the application will call url for kill session login

### ISSUE THREAD

**Issue by nghiepvo** [tale/headplane#262]
### Description

I suggest that we should make a end_session_endpoint in config.yaml
```yml
oidc:
   ....
  # if provide a endpoint after logout from Headplane, the next step will be redirect to endpoint end session.
   end_session_endpoint: "https://auth.example.com/application/o/headplane-oidc/end-session/"
```
