### ISSUE TITLE
OIDC: Cannot connect with Tailscale Clients to Headscale with config from guides

### ISSUE THREAD

**Issue by ragchuck** [tale/headplane#57]
Hi guys,

awesome project, this looks much nicer than the alternatives.

However I encountered a very strange error, while configuring Headscale + Headplane with Authelia OIDC:

I'm using the using the Docker integration and configured  he headscale and headplane as described in the Docker integration guide [here](https://github.com/tale/headplane/blob/main/docs/integration/Docker.md) and [here](https://github.com/tale/headplane/blob/main/docs/Configuration.md).

I can connect to Headplane with Authelia-SSO and everything works as expected.

Unfortunately with the given OIDC settings I cannot connect using Tailscale Clients to the headscale coordination server. I tested with iOS app and Windows Tailscale client.
I found a setting which fixes this issue. But this "fix" breaks the connectivity with headplane.

According tho this error message (see below) I configured the Authelia client settings and added:
```yml
token_endpoint_auth_method: 'client_secret_post'
```

<details>
<summary>
<strong>token_endpoint_auth_method: 'client_secret_basic'</strong>

❌ I cannot connect to Headscale
✔️ I can connect to Headplane
</summary>

**Headscale error:**
> Could not exchange code for token error="oauth2: \"invalid_client\" \"Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method). The request was determined to be using 'token_endpoint_auth_method' method 'client_secret_post', however the OAuth 2.0 client registration does not allow this method.\""

**Authelia error:**
> Access Request failed with error: Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method). The request was determined to be using 'token_endpoint_auth_method' method 'client_secret_post', however the OAuth 2.0 client registration does not allow this method. The registered client with id 'headscale' is configured to only support 'token_endpoint_auth_method' method 'client_secret_basic'. Either the Authorization Server client registration will need to have the 'token_endpoint_auth_method' updated to 'client_secret_post' or the Relying Party will need to be configured to use 'client_secret_basic'." method=POST path=/api/oidc/token remote_ip=172.21.0.1
</details>

<details>
<summary>
<strong>token_endpoint_auth_method: 'client_secret_post'</strong>

✔️ I can connect to the Headscale
❌ I cannot connect to Headplane
</summary>

**Headplane Error:**
> Error: Invalid response from the OIDC provider
    at finishOidc (file:///app/build/server/index.js:6977:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async callRouteLoader (file:///app/build/headplane/assets/index-ZVdnb7Ap.js:39932:16)
    at async file:///app/build/headplane/assets/index-ZVdnb7Ap.js:38325:19
    at async callLoaderOrAction (file:///app/build/headplane/assets/index-ZVdnb7Ap.js:38390:16)
    at async Promise.all (index 0)
    at async defaultDataStrategy (file:///app/build/headplane/assets/index-ZVdnb7Ap.js:38253:17)
    at async callDataStrategyImpl (file:///app/build/headplane/assets/index-ZVdnb7Ap.js:38284:17)
    at async callDataStrategy (file:///app/build/headplane/assets/index-ZVdnb7Ap.js:38095:19)
    at async loadRouteData (file:///app/build/headplane/assets/index-ZVdnb7Ap.js:38073:19)

**Authelia error:**
> Access Request failed with error: Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method). The request was determined to be using 'token_endpoint_auth_method' method 'client_secret_basic', however the OAuth 2.0 client registration does not allow this method. The registered client with id 'headscale' is configured to only support 'token_endpoint_auth_method' method 'client_secret_post'. Either the Authorization Server client registration will need to have the 'token_endpoint_auth_method' updated to 'client_secret_basic' or the Relying Party will need to be configured to use 'client_secret_post'." method=POST path=/api/oidc/token remote_ip=172.21.0.1
</details>

This is my configuration:

<details>
<summary>Autheila Config</summary>

```yaml
# configuration.yaml - Autheila
identity_providers:
  oidc:
    # hmac_secret: # read from ENV
    jwks:
      - key_id: 'authelia'
        algorithm: 'RS256'
        use: 'sig'
        certificate_chain: |
          {{- fileContent "/run/secrets/authelia_identity_providers_oidc_jwks_cert" | nindent 10 }}
        key: |
          {{- fileContent "/run/secrets/authelia_identity_providers_oidc_jwks_key" | nindent 10 }}
    enable_client_debug_messages: false
    minimum_parameter_entropy: 8
    enforce_pkce: 'public_clients_only'
    enable_pkce_plain_challenge: false
    enable_jwt_access_token_stateless_introspection: false
    discovery_signed_response_alg: 'none'
    discovery_signed_response_key_id: ''
    require_pushed_authorization_requests: false
    lifespans:
      access_token: '1h'
      authorize_code: '1m'
      id_token: '1h'
      refresh_token: '90m'
    cors:
      endpoints:
        - 'authorization'
        - 'token'
        - 'revocation'
        - 'introspection'
      allowed_origins:
        - '*'
      allowed_origins_from_client_redirect_uris: false
    clients:
      - client_name: 'Headscale and Headplane'
        client_id: 'headscale'
        client_secret: '[REDACTED]'
        public: false
        authorization_policy: 'two_factor'
        consent_mode: 'implicit'
        redirect_uris:
          - 'https://vpn.domain.tld/oidc/callback'
          - 'https://vpn.domain.tld/admin/oidc/callback'
        scopes: 
          - 'openid'
          - 'profile'
          - 'email'
        userinfo_signed_response_alg: 'none'
        # token_endpoint_auth_method: 'client_secret_post' # -> works only with tailscale iOS app // Headplane -> Error: Unexpected Server Error
        # token_endpoint_auth_method: 'client_secret_basic' # -> works only with Headplane // Headscale --> Error: Could not exchange code for token
```
</details>

<details>
<summary>Headscale config</summary>

```yaml
# config.yml - Headscale
# headscale supports experimental OpenID connect support,
# it is still being tested and might have some bugs, please
# help us test it.
# OpenID Connect
oidc:
  only_start_if_oidc_is_available: true
  issuer: "https://auth.domain.tld"
  client_id: "headscale"
  client_secret: "[REDACTED]"
  # Alternatively, set `client_secret_path` to read the secret from the file.
  # It resolves environment variables, making integration to systemd's
  # `LoadCredential` straightforward:
  # client_secret_path: "${CREDENTIALS_DIRECTORY}/oidc_client_secret"
  # client_secret and client_secret_path are mutually exclusive.

  # The amount of time from a node is authenticated with OpenID until it
  # expires and needs to reauthenticate.
  # Setting the value to "0" will mean no expiry.
  expiry: 180d

  # Use the expiry from the token received from OpenID when the user logged
  # in, this will typically lead to frequent need to reauthenticate and shoulds
  # only been enabled if you know what you are doing.
  # Note: enabling this will cause `oidc.expiry` to be ignored.
  use_expiry_from_token: false

  # Customize the scopes used in the OIDC flow, defaults to "openid", "profile" and "email" and add custom query
  # parameters to the Authorize Endpoint request. Scopes default to "openid", "profile" and "email".

  scope: [ "openid", "profile", "email" ]
  extra_params:
    domain_hint: domain.tld

  # List allowed principal domains and/or users. If an authenticated user's domain is not in this list, the
  # authentication request will be rejected.

  allowed_domains:
    - domain.tld

  # Note: Groups from keycloak have a leading '/'
  # allowed_groups:
  #   - vpn

  # allowed_users:
  #   - alice@example.com

  # If `strip_email_domain` is set to `true`, the domain part of the username email address will be removed.
  # This will transform `first-name.last-name@example.com` to the user `first-name.last-name`
  # If `strip_email_domain` is set to `false` the domain part will NOT be removed resulting to the following
  # user: `first-name.last-name.example.com`

  strip_email_domain: true
```
</details>

<details>
<summary>Compose config</summary>

```yaml
services:
  headscale:
    image: headscale/headscale:0.23
    restart: unless-stopped
    container_name: headscale
    command: serve
    ports:
      - "8080:8080"
      - "9090:9090"
    expose:
      - 8080
      - 9090
    volumes:
      - ./config:/etc/headscale
      - ./data:/var/lib/headscale
    networks:
      - proxynet
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  
  headplane:
    depends_on:
      - headscale
    container_name: headplane
    image: ghcr.io/tale/headplane:0.3.5
    restart: unless-stopped
    volumes:
      - './data:/var/lib/headscale'
      - './config:/etc/headscale'
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - '3000:3000'
    environment:
      # This is always required for Headplane to work
      COOKIE_SECRET: '[REDACTED]'

      HEADSCALE_URL: 'https://vpn.domain.tld'
      HEADSCALE_INTEGRATION: 'docker'
      HEADSCALE_CONTAINER: 'headscale'
      DISABLE_API_KEY_LOGIN: 'true'
      HOST: '0.0.0.0'
      PORT: '3000'
        
      # Only set this to false if you aren't behind a reverse proxy
      COOKIE_SECURE: 'false'

      # Overrides the configuration file values if they are set in config.yaml
      # If you want to share the same OIDC configuration you do not need this
      # OIDC_ISSUER: 'https://auth.domain.tld'
      # OIDC_CLIENT_ID: 'headscale'
      # OIDC_CLIENT_SECRET: '[REDACTED]'

      # This NEEDS to be set with OIDC, regardless of what's in the config
      # This needs to be a very long-lived (999 day) API key used to create
      # shorter ones for OIDC and allow the OIDC functionality to work
      ROOT_API_KEY: '[REDACTED]'
    networks:
      - proxynet
```
The comment about OIDC / ROOT_API_KEY left me a bit confused. I just created an API key using the cli, but there was no OIDC involved....
</details>

Any Ideas?
