### ISSUE TITLE
EntraID OIDC Not Properly Limiting Access

### ISSUE THREAD

**Issue by SysAdminSmith** [tale/headplane#83]
Good afternoon.  First and foremost,  thank you for this awesome product.

I am having issues with limiting access to Headplane.  I fully admin I may be misunderstanding things which may be the cause of the issue.

I have configured EntraID OIDC to work with Headscale via the config file.  However, I don't want everyone who has access to headscale to have access to Headplane.  So, in my docker compose, I make reference to a different EntraID Enterprise App w/ OIDC so I can have admin users that are the only users that have access to Headplane.  

Unfortunately, it seams that anyway who can authenticate against the tenant can get into headplane.

Group_A is set to have access to headscale via the config.
Group_B is set to have access to headplane via the docker_compose environmental variables.  

Anybody (whether in either Group_A or Group_B) can access Headplane.  I suspect its because of a token stuck in my browser?

Here are my configs (in pertinent part):

conf/config.yaml:
```

oidc:
  only_start_if_oidc_is_available: true
  issuer: "https://login.microsoftonline.com/tenantnumbers/v2.0"
  client_id: "Client_ID_A_Numbers"
  client_secret: "SECRETNUMBERS"
  scope: [ "openid", "profile", "email" ]
  extra_params:
    domain_hint: bar.com
    prompt: select_account
  allowed_domains:
    - bar.com
  allowed_groups:
    - "GROUP_A_NUMBERS"
  strip_email_domain: false
```

docker_compose.yml:
```

  headplane:
    image: ghcr.io/tale/headplane:latest
    container_name: headplane
    restart: unless-stopped
    environment:
      - LOAD_ENV_FILE=true
      - HEADSCALE_INTEGRATION=docker
      - HEADSCALE_CONTAINER=headscale
      - OIDC_ISSUER=https://login.microsoftonline.com/tenantnumbers/v2.0
      - OIDC_CLIENT_ID=Client_ID_B_Numbers
      - OIDC_REDIRECT_URI=https://foo.bar.com/admin/oauth/callback
      - ALLOWED_GROUPS=GROUP_B_NUMBERS
      - TZ=America/New_York
      - HEADSCALE_URL=http://headscale:8080
      - COOKIE_SECRET=Numbers
      - OIDC_CLIENT_SECRET=Numbers
      - ROOT_API_KEY=Numbers
      - COOKIE_SECURE=true
      - DEBUG=false
      - DISABLE_API_KEY_LOGIN=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./conf:/etc/headscale
      - headscale-data:/var/lib/headscale
    ports:
      - "3000:3000"
    networks:
      - FooBarAzureInfrastructure
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=FooBarAzureInfrastructure"
      - "traefik.http.services.headplane.loadbalancer.server.port=3000"
      - "traefik.http.services.headplane.loadbalancer.server.scheme=http"
      - "traefik.http.routers.headplane.rule=Host(`foo.bar.com`)"
      - "traefik.http.routers.headplane.entrypoints=websecure"
      - "traefik.http.routers.headplane.tls=true"

```

Any ideas?  Thank you!
